blueprint:
  name: Bathroom Fan
  description: >
    # 🚿🚽 Bathroom Exhaust Fan

    ** Version 2.0 **

    I created this blueprint based on my experience with short-term rentals at my home. With short stays, you occasionally get tenants who might not be as mindful of upkeep—likely because they’re unfamiliar with the space, right? With that in mind, I’ve worked to make the setup as convenient and intuitive as possible, while still maintaining a sense of luxury. For instance, I've included a feature that triggers an action when the fan is turned on or off. I personally use it to control a [Pura diffuser](https://pura.com/), giving guests peace of mind and ensuring the space stays fresh for whoever comes next 🚽💩.

  Huge thanks to [Blacky](https://community.home-assistant.io/u/blacky/summary) and his blueprints, which helped a lot in creating this blueprint.

  <details>
    <summary><b>My The Automation Proccess:</b> 👆</summary>
    
  </details>  

  Required = *
  domain: automation
  source_url: https://github.com/OsulivanAB/home-assistant/blob/bahtroom_fan/blueprints/Bathroom_Fan.yaml
  author: Anthon Bahl (@AnthonyBahl)
  homeassistant:
    min_version: 2024.9.3

  input:
    trigger_settings:
      name: "Auto Triggers *"
      icon: mdi:cog-outline
      description: These triggers are automatic and require no intervention by the bathroom user. 🤖
      collapsed: true
      input:
        derivative_sensor:
          name: Humidity Derivative Sensor *
          description: Select your humidity derivative sensor.
            This trigger will be used to determine if someone is showering or not, and will dynamically also tell us when to turn off the fan.

            Derivatives are a great way to determine if a sensor is increasing or decreasing.
            In this case, we are using it to determine if the humidity is increasing or decreasing more rapidly than it normally does.
            If the humidity derivative is increasing at a rate higher than it typically changes, we can assume someone is showering. 
            If the himiddity derivative is decreasing at a rate higher than it typically changes, we can they're done.
            When it returns to a normal rate of change, we can assume the fan is no longer needed.
          selector:
            entity:
              domain: sensor
              device_class: humidity
mode: restart